name: test

on:
  workflow_call:

env:
  PROJECT_PATH: tests\AllSales.Console.UnitTests\AllSales.Console.UnitTests.csproj

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.PROJECT_PATH}}
    - name: Build
      run: dotnet build ${{env.PROJECT_PATH}} --configuration Release --no-restore
    - name: Test
      run: dotnet test ${{env.PROJECT_PATH}} --no-build --verbosity normal
