name: unit_tests_cumulative

on:
  workflow_call:

env:
  TEST_PROJECT_PATH: tests/AllSales.Console.UnitTests/AllSales.Console.UnitTests.csproj

jobs:
  AllSales_Console_UnitTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ${{env.TEST_PROJECT_PATH}}

    - name: Build
      run: dotnet build ${{env.TEST_PROJECT_PATH}} -c Release --no-restore
      
    - name: Test
      run: dotnet test ${{env.TEST_PROJECT_PATH}} -c Release --no-build --verbosity normal
